### ISSUE TITLE
Astral - Marbel

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#10]
https://user-images.githubusercontent.com/88991962/207123026-6828b0c4-de97-4883-bd72-3fcda49d363c.mp4

Como não tem mineradora, nem forma de fazer, sugiro essa ser uma receita pra ela, pedra infundida no liquidos das estrelas...

**Comment by ArtpokeBr** [comment]
Marble Refinado já é feito usando o Marble comum, que por sua vez pode ser feito num Igneous Extruder. não sei se notou kkk
