### ISSUE TITLE
Macarrão Tinkers

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#102]
![image](https://user-images.githubusercontent.com/88991962/226792467-196a9eb2-db68-426e-90aa-6b59d42f8201.png)

Achei ele, mas não tem como secar, nem do tinkers nem do pyro

![image](https://user-images.githubusercontent.com/88991962/226792547-3eee0519-169c-4a42-bb2f-012f296b6674.png)

**Comment by ArtpokeBr** [comment]
Onde achou?

**Comment by Gkiritol** [comment]
Olha não lembro ao certo, mas a única estrutura que achei foi as Rogue Like Dungeons
