### ISSUE TITLE
Quest add - drawers

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#111]
Sugiro add uma quest pros drawers 
falando sobre suas variantes e sobre a varinha 
já q com @drawers, não a encontramos

**Comment by ArtpokeBr** [comment]
Fica como um pequeno item de segredinho :p Adicionado como recompensa da Quest do Compacting Drawer e a devida explicação de como funciona está no JEI.
