### ISSUE TITLE
Forestry + chisel

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#114]
![image](https://user-images.githubusercontent.com/88991962/229944259-2ba9f3d4-9095-4cc1-ba2e-da4619de8801.png)

![image](https://user-images.githubusercontent.com/88991962/229944298-c4f3c5f0-7f15-461e-9099-38b79f6e059d.png)

Sugiro colocar eles no chisel para poder mudar as texturas 
das 4 partes no caso

**Comment by ArtpokeBr** [comment]
Os Blocos para antes de serem convertidos em Farms do Forestry podem ser facilmente chiselados entre si, então seria meio redundante adicionar também uma receita de chiseling.
