### ISSUE TITLE
Sulfur mob drop

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#121]
Os mobs ainda continuam a dropar sulfur, mas agora ele não tem utilidade 
![image](https://user-images.githubusercontent.com/88991962/230750560-c9059677-be78-4318-aa36-89414b3e7283.png)

**Comment by ArtpokeBr** [comment]
Faça uma lista dos que ainda droppam.

**Comment by Gkiritol** [comment]
Bom mais simples é vc seguir essa etapa:
1: pesquise Gunpowder no hei
2: Clique na abelha na aba de pesquisa
3: Rode o scrool até aparecer 1 com drop de sulfur
4: clique com o botão esquerdo no sulfur  e gg
