### ISSUE TITLE
Botania - Gaia 

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#122]
Para invocar o Gaia precisa de Terrasteel 
Só q no pluma a prioridade de oredict está o GT
Assim o ingot vira o do GT
Oq é incompatível com o do botania, tornando assim impossível invocar o Gaia no pluma

**Comment by ArtpokeBr** [comment]
Eita, curioso isso, eu cheguei a organizar as receitas do Botania, mas n testei a invocação da Gaia em si, tristeza isso kkkk

**Comment by Gkiritol** [comment]
Sugiro ou vc fazer uma conversão "in game"
Tipo chisel ou um "dicionário"

Ou Fazer uma receita de conversão 

Tipo o item é jogar ele na mana pool pra ter a forma de invocar
