### ISSUE TITLE
IMP

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#130]
Estou tendo muita dificuldade em achar IMP 
![image](https://user-images.githubusercontent.com/88991962/232350973-2a790273-d32a-477c-ba95-19898081f4d9.png)

Ele é um mob pacifico, e está dividindo spawm com o mob do libworld e perdendo pelo visto, eu matei mais de 100 desses caras e não vi 1 imp em mais de 1 hora. 

Posso estar com muito azar, mas...

**Comment by ArtpokeBr** [comment]
Tentou spawnar com o Roots?

**Comment by Gkiritol** [comment]
Bom art, aí não seria problema o problema relatado em si, mas não, não testei pq não acho imp pra começar o roots
