### ISSUE TITLE
Acctually - Farm de lapis

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#14]
![image](https://user-images.githubusercontent.com/88991962/207443906-02889995-fcff-472c-a470-20b1a888f263.png)

Lens of color pode mudar a cor dos objetos...
ela muda cocoa para lapis

**Comment by ArtpokeBr** [comment]
Receitas alteradas e balanceadas levando isso em consideração.
