### ISSUE TITLE
Garrafa de vidro

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#152]
![image](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/88991962/979ce71e-2b39-40f0-9dd5-e18fc2845773)

![image](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/88991962/1e3941f8-a3f8-4db9-8ec7-8e006b57959a)

Vc fazendo na mesa ganha a do binnie, muda a ordem e deixa a vanila primeiro, a do binnie é "inutil"

**Comment by ArtpokeBr** [comment]
Tem utilidade, é usado para engarrafar os Licores do Binnies. o que eu preciso fazer é remover a receita em si e deixar apenas a possibilidade de conversão.
