### ISSUE TITLE
Cap 5  - LP

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#158]
Sugiro add umas quests 
tipo "dev tips"

![image](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/88991962/4dd3a0f9-aa69-4f57-962c-7c3b6fac5f88)
Vc pode por exemplo fazer 1 unica conexão com o storage assim e receber e mandar itens

**Comment by ArtpokeBr** [comment]
Mais um caso que sinto que seria complicado adicionar peso de Quests pra uma  coisa que o Player deve saber fazer.

No caso, já provi um extenso tutorial no formato de Quests pro LP. e no final você sempre pode dar essas dicas pra eles caso perguntem no Discord :p
