### ISSUE TITLE
Brick Wooden Form, Coke Oven cyclic recipe lock (+Tanning Rack uncraftable before coke oven)

### ISSUE THREAD

**Issue by bluegreen1024** [ArtpokeBr/Pluma-a-Journey-to-the-Future#162]
The coke oven bricks require the wooden form which requires metal GregTech saws, which require metal plates and hammers, which requires blacksmithing, which comes after the coke oven in the quest progression and indirectly requires the coke oven. Also, the tanning rack needs treated wood products which needs the coke oven, even though the tanning rack comes before it in the quests (because leather is needed for bellows, and tanning rack is needed for leather.

This is either an outright progression lock due to cyclic recipes, or the intended recipe progression is different from what the quest line says it is. However I looked through HEI recipes as well as the quest line, and all the recipes I found require the coke oven in order to make the coke oven.

**Comment by ArtpokeBr** [comment]
Ok, I'll take a look =)

**Comment by ArtpokeBr** [comment]
Well it seems that you've got confused a bit haha

**Comment by ArtpokeBr** [comment]
![image](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/44851727/fda0a01b-5c72-4abb-8aea-513a06157d31)
Crushing Table Recipe to make early game plates (use them to make a saw)
What i've noticed tho is that to make it more clear that you must progress in other quests, I'll restrict the "Making Coke Bricks" Quest to after you've assembled your first tools.

**Comment by ArtpokeBr** [comment]
![image](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/44851727/e2f494f1-1d2a-462c-ad03-8575eb10196a)
Improving Quests beacuse of this btw =)

**Comment by bluegreen1024** [comment]
That makes it much clearer, thanks!
