### ISSUE TITLE
Tinker tool leveling gives random modifiers not unused modifier slots. Is this intended?

### ISSUE THREAD

**Issue by bluegreen1024** [ArtpokeBr/Pluma-a-Journey-to-the-Future#165]
I've never seen this behavior before in a modpack, and it is both funny and frustrating (my sword has hovering!). I thought I would report it in case it is a bug

**Comment by ArtpokeBr** [comment]
Oh, no worries, this is intended! as a way to balance Tinker's a thought it would be interesting to have this instead of huge XP Requirements for Extra Modifiers.

So far, what do you think about this feature?

**Comment by bluegreen1024** [comment]
Personally, I don't like it very much. Given how many modifiers there are to choose from, and how most of them are not good on any particular tool, it is almost as if the tool leveling isn't there. It is true you might get lucky, but much more likely you will get useless modifiers. 
However I agree with you that Tinker's tool leveling is unbalanced by default. I recall a mod that made it so that extra modifiers were something you had to craft (with increasingly expensive materials), and I like that concept better, but I can't remember the name of that mod. 
Anyway it is not game-breaking, so if you want it to work that way that's fine. I just wanted to check that it wasn't a bug.

**Comment by ArtpokeBr** [comment]
Well, there is a way for me to configure it to only give certain modifiers.

Tbh, I feel like its an interesting way to give players certain modifiers that they wouldn't "waste resources" to craft. I've never saw someone actually apply Levitating for example haha.

Also, there is currently an addon to Tinker's in the pack that you can use to "craft extra modifier slots" ;)

**Comment by bluegreen1024** [comment]
That's what I was thinking of! I didn't realize it was in the pack, but it will be helpful.
