### ISSUE TITLE
Suggestion: Pack normal mode toggle

### ISSUE THREAD

**Issue by wisheth** [ArtpokeBr/Pluma-a-Journey-to-the-Future#166]
I've been looking for a new 1.12 kitchen sink pack to play on a private server I host and stumbled across Pluma; while the expert progression seems very demanding for a lot of the players, the mod list seems like exactly what I've been looking for. If it's not too much effort, it would be nice to have a pack mode toggle to allow the pack to be played without (heavy) progression such that recipes are unified and recipes throughout the pack aren't heavily gated.

**Comment by ArtpokeBr** [comment]
I've added a "Easy Mode" World Gen, and with that, that's exactly what i've been thinking haha

"Wouldn't be cool to add an Easy and Chill Mode just like Omnifactory?"

But unfortunatly, while I would like to implement such mode, currently my priority is to finish the normal and intended way to be played, currently, the next patch is going to be a big one in terms of quests, been working in a lot of them.
