### ISSUE TITLE
Super Pattern Chest Bugado

### ISSUE THREAD

**Issue by CreamChocolateCookies** [ArtpokeBr/Pluma-a-Journey-to-the-Future#168]
Quando você quebra o "super pattern chest" ele, ao invés de dropar devolta um pattern chest com todos os patterns, ele dropa uma crafting station.

https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/138946388/228308c6-c0de-4bc2-865e-4773bce86c5b

**Comment by ArtpokeBr** [comment]
Bem esquisito esse comportamento, terei de investigar quando for possível.
