### ISSUE TITLE
Receita de bote do GT com problema

### ISSUE THREAD

**Issue by CreamChocolateCookies** [ArtpokeBr/Pluma-a-Journey-to-the-Future#169]
Os os botes do GT, mais especificamente os botes de rubber wood e treated wood, estão com receitas impossíveis de serem feitas, pois, não existe nenhuma forma de se fazer uma pá de madeira.
![receita do bote 1](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/138946388/d6bd247a-8664-4d78-b7c6-195781f4b984)
![receita do bote 2](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/138946388/a87feeb7-e877-448c-a770-d2ec8a561343)
![pesquisa de pá de madeira](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/138946388/44be1ab9-efad-4d39-8245-bcf143664128)

**Comment by ArtpokeBr** [comment]
Ok, probleminha fácil de resolver, só ajeitar a recipe.
