### ISSUE TITLE
Abelhas e Plastic do Industrial

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#170]
![image](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/88991962/6df50da5-0cdd-4761-b756-97dd3a82ec9a)

![image](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/88991962/53005656-c56b-4573-969b-7cd39b46d721)

Sugiro remover a receita desse comb no centrifuge e no centrifugal separator. E colocar ele no Chemical Reactor junto de sulfur para gerar plástico.

se achar pouco, poderia ser assim:

comb + centrifugal separator = dry rubber + 250mb de latex 

Obs.: A abelha que gera esse comb não tem receita.

Como planejo add ela no jogo então? tem como o player a partir de 1 drone, criar uma rainha dessa espécie. então dá pra ter ela infinita.

Eu pensei em dar ela em uma das ultimas quests do caminho da abelha (usando /give)  (podendo pedir dinheiro tbm)
assim o cara teria q aprender a usar bem o forestry pra não fazer besteira kkkk

**Comment by ArtpokeBr** [comment]
![image](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/44851727/50a2124b-e20d-454f-b78c-2a44dbfcb2a5)
Achei numa Wiki, dá uma testada.

**Comment by ArtpokeBr** [comment]
O Gregtech atualmente já possui integração com as Abelhas, vou fechar o Issue pois vai precisar de uma Reavaliação após eu fazer a atualização pro GT novo.
