### ISSUE TITLE
Thaum - Pesquisas Bloqueado

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#171]
![image](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/88991962/c92e4ec6-8e36-43eb-a6c9-bac8e152d7f7)

![image](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/88991962/671f9249-6877-437a-8f68-459fcc41a686)

Não sei se é de proposito, mas com a Oredict, colocando Brass ZnCu3 sendo igual ao do Thaum, torna impossivel obter o do thaum, sendo impossivel completar a "quest" 

Dessa forma. Sendo IMPOSSIVEL fazer as pesquisas do tham

**Comment by ArtpokeBr** [comment]
Preciso fazer então igual ao Botania, colocar uma receita de conversão pra poder trocar os Ingots.
