### ISSUE TITLE
iChisel não está chiselando os moldes do Tinkers'

### ISSUE THREAD

**Issue by CreamChocolateCookies** [ArtpokeBr/Pluma-a-Journey-to-the-Future#174]
O iChisel não esta funcionando para chiselar os moldes do tinkers'.

https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/138946388/8dba51d0-bac3-42f9-8dcc-116b8b99ccf3

**Comment by ArtpokeBr** [comment]
Um tanto quanto chatinho de pensar numa correção, eu teria que mencionar em algum lugar que a IChisel n funciona bem com os Casts, pois as outras 2 Chisels tão funcionando de boas.
