### ISSUE TITLE
Living tools from Roots cannot be crafted

### ISSUE THREAD

**Issue by fanebanane** [ArtpokeBr/Pluma-a-Journey-to-the-Future#175]
All living tool variants from Roots require the wooden vanilla counterpart in order to be crafted but none of the vanilla wooden tools have a crafting recipe with the exception of the Wooden Sword, rendering most living tools uncraftable. The Forester from Cyclic requires a Living Axe but because the vanilla Wooden Axe has no crafting recipe, it makes the Forester uncraftable.

**Comment by ArtpokeBr** [comment]
Ok! this will definetly be fixed in the next patch! =)

**Comment by ArtpokeBr** [comment]
Fixed, now Wooden Tools can be crafted in an Alternative way!
