### ISSUE TITLE
AA Laser

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#178]
Estava fazendo uns testes em meu mundo usando os lasers (q fiz antes de vc mudar a receita kkkk) 
e descobri um "bug" no mod, se é q posso chamar assim...

quando vc vai aplicar o upgrade de range vc tem q ter 2 no inventário na hora.
quando vc tenta aplicar usando só um, por algum motivo buga e não consta.

assim quando vc faz a receita e vem 2, ao clicar no primeiro com os dois no mesmo slote, vc coloca o upgrade no primeiro, mas quando tenta no segundo ele buga...

sugiro colocar uma quest ou uma tool tip pra isso...

Real não sei o q causa, mas fazendo assim todas as vezes q tentei colocar foi

**Comment by ArtpokeBr** [comment]
Adicionado uma Tooltip para alertar.
