### ISSUE TITLE
Forestry charcoal burning does not work

### ISSUE THREAD

**Issue by hron84** [ArtpokeBr/Pluma-a-Journey-to-the-Future#183]
I dug a 3x2 pit, put down 9 Forestry wood pile, ignited with flint and tinder, covered with dirt but it just burns away. Either Pyrotech and Forestry is colliding on this, or some config issue happens.

**Comment by hron84** [comment]
I dug into a little bit of the modpack's config and scripts and I have a feeling - but I didn't tried to reshape this part of the pack - that forestry wood pile causes the issue. My suggestion is disable forestry charcoal module entirely and make the Pyrotech wood pile to 2x2 recipe instead of 3x3. In this way you will not neccesarily need to override the Pyrotech Burn module.

**Comment by ArtpokeBr** [comment]
Thanks for the report and the Help, I'll take a look when able to =)
