### ISSUE TITLE
Hand Framing Tool

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#187]
Mesmo bug da bowl ali 
![image](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/88991962/189147f7-c62c-4d99-a462-e34dc9fbd662)

Só aceita ferro

**Comment by ArtpokeBr** [comment]
![image](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/44851727/f975ff36-c687-4bd2-9918-bc3c68316aa9)
Funcionando normalmente também, pode ser que seja um problema no LP em relação a isso então.
