### ISSUE TITLE
Quest ainda bloqueada

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#192]
![image](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/88991962/db1b3297-d621-43ba-833e-502c1df97cd2)

![image](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/88991962/8cf24dd4-06ba-4756-9044-eec537bb01ac)

**Comment by ArtpokeBr** [comment]
Putz, Ok, será corrigido também.
