### ISSUE TITLE
Versão 3.6 - Comidas:

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#197]
**Comidas sem receita ou Forma de Obter**

- Juniperberry
- Lychee Tea
- Schnitzel
- Sauced Lamb Kebab
- Cantonese Noodles
- Swedish Meatballs
- Bratwurst
- Roasted MarshMallow
- Ham & Cheese Sandwhich
- SilkWorm
- Bean Stew
- Pork Rinds
- Garlic Steak
- Imitation Crab Sticks
- BBQ JACKFRUIT

**Remover do mod de Nutrição:**

Todos os bolos do Pams

**Comment by ArtpokeBr** [comment]
- Juniper Berry através de Breeding do Forestry (adicionado receita de conversão do Binnies pro HarvestCraft e respectivamente adaptado a receita.)
