### ISSUE TITLE
Add os "Fast" mods

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#209]
![image](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/88991962/e57e0e44-a463-4dd6-87fa-a4fe4144a2d9)

Sugiro add o "Fast Furnace" e o "Fast Work Bench" 

Motivo? 

- Como destacado na print, e dito em live, esses mods da "familia" Fast, eles pegam a última receita feita e colocam ela como prioridade no reconhecimento.

Ex. Pratico

digamos q vc tenha q adivinhar um número aleatório e só pode ir "chutando" em ordem crescente um por vez, se o número fosse o 7, por ex. vc contaria 0 1 2 3 4 5 6 7, assim passando por 8 números até chegar até o 7, no mine em geral assamos mais de 1 item por vez, logo a chance de cairem "dois 7" seguidos seria maior, assim ele muda a prioridade, contando 7 0 1 2 3 4 5 6 8 
Ai caso o 7 seja o escolido ele será o primeiro, assim adiantando o processo

**Comment by ArtpokeBr** [comment]
Teoricamente o Universtal Tweaks já deve desempenhar a função. teria que testar :)

**Comment by ArtpokeBr** [comment]
This type of Feature already exists in Universal Tweaks.
