### ISSUE TITLE
Remoção de mod

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#210]
Sugiro remover esse mod:

![image](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/88991962/63f7b6ca-3362-4db1-94be-d488268cd45a)

Motivo:

![image](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/88991962/c5b133ac-6c22-4676-b338-29769ca05607)

- Ele só add textura em drawer, vc pode até achar bonito, mas gera peso desnecessário. Uma vez q temos o Framed Drawer

**Comment by ArtpokeBr** [comment]
Good reason, but it doesn't seem to impact performance that much to be relevant :)

If you have proof that It does impact performance significantly, I'll remove it in a future update.
