### ISSUE TITLE
Inventory Cake (Cyclic Tool Tip) + Remover mod de Improved Backpacks

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#220]
Code

---------------------------------------------------------------------------------------------------------
item.addTooltip(tT);

cyclicmagic:inventory_food.addTooltip("Controls: → Extended Inventory ( If Unlocked )");

-------------------------------------------------------------------------------------------------------------

É possivel abrir esse inventário do Bolo usando uma tecla, 

Sugiro add essa tool tip (ou silimilar para dizer "ah dá pra usar botão pra acessar"

Em anexo video 

https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/88991962/405beedd-ca0f-4040-abdd-58b315bb80b2

REMOÇÃO:

1º Vc consegue comprar o Inventory upgrade na primeira era de boas

2º tendo outra backpack inutiliza a do forestry

3º com esse atalho q disse anteriormente, o torna uma mochila de 4x9 slotes (36 slotes) 

4º "Ah mas e mochila EV pra colocar as minhas coisas" Tem o ender Utilities com aquelas mochilas dele 

então o mod em questão é desnecessário

**Comment by ArtpokeBr** [comment]
Muitos estão usando as Backpacks do Improved Backpacks, depois de uma votação no Discord, decidi não alterar isso.
