### ISSUE TITLE
quest de circuitos 

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#229]
Add uma aba de quests q nem a do GTNH ajuda dms a se localizar 

Se quiser algo mais simples, tipo os 3 LV em uma quest e falando oq cada um é

seu primeiro circuito

seu intermediario

seu definitiivo

Automatize esse

**Comment by ArtpokeBr** [comment]
Currently in the works. should get released as the progression is also done.
