### ISSUE TITLE
[Pack] [Bug] FTB ultimine 

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#23]
A troca dos modos de "vein miner" não aparecem no canto superior esquerdo. Assim quando o player troca (mesmo q por acidente o "vein miner" não funciona como deveria)

**Comment by ArtpokeBr** [comment]
Oxi, ok, verificarei, na pior das hipóteses, troco o Mod.
