### ISSUE TITLE
Versão 4.0 Mods "Repetidos"

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#231]
Temos 2 mods que fazem a mesma função 

![image](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/88991962/9c8e53e1-da77-460d-b30d-d442d4fb83fa)

![image](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/88991962/1f0e837c-140a-4e7e-bebd-7366fef7e03a)

**Comment by ArtpokeBr** [comment]
Tecnicamente Não, mas tudo bem kkkk
