### ISSUE TITLE
Update 4.0 Conflito de recipe

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#232]
![image](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/assets/88991962/d6dd3984-1b8a-4821-9aa6-d8428ca06f08)

Add um circuito

**Comment by ArtpokeBr** [comment]
Não tem como Adicionar um Circuito, não tem Slot pra isso :/
