### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Z1664291187** [ArtpokeBr/Pluma-a-Journey-to-the-Future#242]
Hello, I like your Modpacks very much. I hope you don't give up. Supersymmetry, MeatballCraft and Technological Journey are all very good Modpacks. I hope to give you inspiration. Come on, you can do it! Don't give up

**Comment by ArtpokeBr** [comment]
No worries, its just a lack of time to actually keep developing this personal project =)

If you like my work, feel free to check out the modpack called FTB Interactions Remastered, I worked a lot to bring the remastered version to light and I'am currently working for FTB, so almost all projects released by them have a little bit of my work and help =)
