### ISSUE TITLE
Desync de Inventário

### ISSUE THREAD

**Issue by Stiink11** [ArtpokeBr/Pluma-a-Journey-to-the-Future#25]
Hoje quando baixei o modpack para jogar ir testando tive logo no início um desync de inventário, na live de sexta vi um pessoal comentando que tinha também sofrido com esse bug, nos teste que fiz aqui o desync so ta acontecendo quando eu aloco mais de 6,8 gb de memória ram, no meu caso na primeira vez eu tinha alocado 12gb.

**Comment by ArtpokeBr** [comment]
obrigado pelo report, outro já foi aberto com um problema similar, vou ver se consigo resolver por lá =)
