### ISSUE TITLE
Desync de inventario

### ISSUE THREAD

**Issue by Losangulo** [ArtpokeBr/Pluma-a-Journey-to-the-Future#26]
Eu não consigo jogar pois estou com desync de inventario, já tentei mudar a ram como tinham falado, mas não funciona, já testei com 8, 7, 6, 5 e 4 de ram e sempre da no mesmo

**Comment by Losangulo** [comment]
Isso estava acontecendo antes e depois do update

**Comment by ArtpokeBr** [comment]
Por favor, tente jogar, e depois me mande o último Log. pra ver se eu consigo encontrar o Motivo.

**Comment by Losangulo** [comment]
[latest.log](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/files/10298923/latest.log)

**Comment by Losangulo** [comment]
Eu criei outro mundo depois do update e esse log é desse novo mundo mas o problema continua

**Comment by ArtpokeBr** [comment]
Atualize para a versão mais recente a Beta 1.2 e por favor, tente remover o Mod Sound Physics, veja se isso ajuda no seu caso.

**Comment by Losangulo** [comment]
ok

**Comment by Losangulo** [comment]
não esta aparecendo para atualizar
![image](https://user-images.githubusercontent.com/75524726/209451048-60c3005d-e188-4033-99b8-5154d1b29102.png)

**Comment by ArtpokeBr** [comment]
Desmarque a opção que permite adicionar Mods.

**Comment by Losangulo** [comment]
blz

**Comment by Losangulo** [comment]
atualizei e tirei o mod Sound Physics mas continua o mesmo

**Comment by Losangulo** [comment]
[latest.log](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/files/10299233/latest.log)

**Comment by ArtpokeBr** [comment]
Quanto de RAM no momento você está usando?, notei também pelo Log que você chegou a se teleportar, algum tipo de lagzinho durante isso é normal. o que não é é ter desync a todo momento mesmo estando parado em sua base ou algo assim e tal.

**Comment by Losangulo** [comment]
eu estou com 5 de ram mas estava acontecendo ainda quando eu testei com 6, 7 e 8 de ram, eu estava de boa na base craftando coisas e dunada deu isso denovo

**Comment by ArtpokeBr** [comment]
Sobe pra 6 por segurança, mas eu sinceramente não sei o que exatamente está acontecendo no seu caso. Analisando os Logs, não tem nada fora do comum aparente. se bobear pode até ser perfomance de seu computador =/

**Comment by Losangulo** [comment]
Eu vou dar uma saída agora e depois testo isso de colocar 6 de ram mas isso é estranho, eu todo DJ2 sem nenhum problema. Eu vou tentar jogar gravando para ver se é algo que eu faço dentro do jogo que desencadeia esse bug

**Comment by ArtpokeBr** [comment]
Ok! obrigado pela compreensão, juro que to tentando lhe ajudar com o que sei kkk

**Comment by Losangulo** [comment]
Eu que tenho que agradecer kkk, em plena véspera de natal e você aqui ajudando kk

**Comment by ArtpokeBr** [comment]
O Bug ainda persiste? só pra saber se posso fechar o Issue :)

**Comment by Losangulo** [comment]
Pode fechar, vlw ae
