### ISSUE TITLE
Missing Item - Archaeologist Hat

### ISSUE THREAD

**Issue by MasterT0ad** [ArtpokeBr/Pluma-a-Journey-to-the-Future#27]
O item "Archaeologist Hat" da quest inicial está com problemas, não sendo possível equipar, segue a print mostrando o problema

![image](https://user-images.githubusercontent.com/121360137/209453904-d7158d79-d93c-43c7-b6c8-bde3d5bd41ed.png)

**Comment by MasterT0ad** [comment]
btw, versão BETA 1.2

**Comment by ArtpokeBr** [comment]
Sim Sim, verifiquei isso, o item será removido das recompensas iniciais, já foi corrigido, obrigado pelo report =)
