### ISSUE TITLE
Recompensa da primeira quest pós update beta 1.2

### ISSUE THREAD

**Issue by Stiink11** [ArtpokeBr/Pluma-a-Journey-to-the-Future#28]
Não é bem um bug, acho que até ta no ultimo changelog, o archeologist hat, ainda ta dando como recompansa la na primeira missão do pack, criei um novo mundo como ele ta desabilitado o item que da na missão vem igual ta na print.
![image2](https://user-images.githubusercontent.com/121344535/209454763-46aab62d-0ad8-4174-b815-462b9bfb8979.png)

![image](https://user-images.githubusercontent.com/121344535/209454732-e2b2e12a-aeb3-401e-90ec-06066717ece0.png)

**Comment by ArtpokeBr** [comment]
Pode ficar tranquilo, já foi identificado, e corrigido no próximo patch que está por vir =)
