### ISSUE TITLE
Obsidian (early game)

### ISSUE THREAD

**Issue by Dewn5228** [ArtpokeBr/Pluma-a-Journey-to-the-Future#29]
### Problema

1. Não consegui encontrar nenhuma forma de fazer obsidian no early game (sem diamantes/outros recursos, não tentei exploração de dungeons).
 
2. Não existe uma recipe no jei de como fazer obsidian shards (utilização: obsidian cog usada no smeltery controller).

### Prints/Videos

![Cog](https://user-images.githubusercontent.com/109928715/209673486-d224347f-c11d-4ca5-96b2-042c18183f54.png)

![smeltery controller](https://user-images.githubusercontent.com/109928715/209673496-8d9022e5-41e7-4242-93c6-47a12a44b100.png)

https://user-images.githubusercontent.com/109928715/209673873-761a3621-955a-494d-9923-e36cfa966701.mp4

**Comment by ArtpokeBr** [comment]
Já foi corrigido, e virá no próximo Patch =)
