### ISSUE TITLE
Bug na receita do vidro com shards

### ISSUE THREAD

**Issue by Kraties13** [ArtpokeBr/Pluma-a-Journey-to-the-Future#34]
Não é possível craftar o bloco de vidro usando a crafting table 2x2 do inventário mesmo tendo a mesma quantidade 
![2022-12-31_16 52 50](https://user-images.githubusercontent.com/103679117/210154998-b5b5cede-c5f5-43d6-9b71-876d751ed716.png)
![2022-12-31_16 52 46](https://user-images.githubusercontent.com/103679117/210155001-45f6904a-7836-4058-ac01-50ce13c28402.png)

**Comment by ArtpokeBr** [comment]
Ok! será trabalhado assim que possível, e virá no próximo Patch =)
