### ISSUE TITLE
Automated Belows require Piston

### ISSUE THREAD

**Issue by Lushtub** [ArtpokeBr/Pluma-a-Journey-to-the-Future#35]
Automated Belows require a piston in their crafting recipe.
![image](https://user-images.githubusercontent.com/65468358/210197165-700855dd-c20d-4d17-8713-e0d1eb78c2e8.png)
The problem is, to make a piston, red alloy is required.
![image](https://user-images.githubusercontent.com/65468358/210197190-24591816-52a0-498f-9af0-934a06fff8c4.png)
Red alloy can't be made at the stage of the game where the quest is accessible. I think there should be a way to make it early on, as you require at least steam machines to make some.

**Comment by ArtpokeBr** [comment]
Ok! thx for the report. I'll take a look at it will probally be fixed in the next patch.

**Comment by ArtpokeBr** [comment]
Fixed, now Red Alloy Dust can be done by hand, then smelt in a furnace to get the ingots =)
