### ISSUE TITLE
Lunch bag, Baykok, Backpack and double recipes

### ISSUE THREAD

**Issue by Lushtub** [ArtpokeBr/Pluma-a-Journey-to-the-Future#38]
-The paper lunch bag requires wood pulp, which needs at least steam machines to craft
-While the problem with Baykok's bow not being used anywhere is fixed, I don't get why the nether quest requires killing him
-This is more of a suggestion, but I think the backpack is a bit far in progression (It's gated in LV)
-Some vanilla items have two crafting recipes, one by pyrotech and the other one by GT (Such as the bow, saddle, book, etc)

**Comment by ArtpokeBr** [comment]
Could you please investigate further about this recipes overlaping? Pyrotech ones and GT and etc.

**Comment by Lushtub** [comment]
Some vanilla items have more complex recipes for more realism added by pyrotech and GT, for example the bow. So, i'd just suggest removing one of the two using its recipe id. These "doubled" recipes are occurring most of the time with recipes that require leather, as both mods will try to rework them.
