### ISSUE TITLE
Quest's "The process of making Dark Steel Part I e Part II"

### ISSUE THREAD

**Issue by Dewn5228** [ArtpokeBr/Pluma-a-Journey-to-the-Future#47]
### Problema

Nas quest's "The process of making Dark Steel Part I" e "The process of making Dark Steel Part II" tem dust's do mekanism, os quais não podem ser feitos nessa "era" e que tambem não funcionam nos craft's.

Sei que não funcionam porque para não atrapalhar a minha progressão dei give nos dust's.

### Imagens/Preview
![Screenshot_1](https://user-images.githubusercontent.com/109928715/210675002-a92d80f0-3b5f-4849-a20a-ea73c0e54903.png)

![Screenshot_2](https://user-images.githubusercontent.com/109928715/210675006-8550677a-bb2f-458d-b4a5-885cbd0ff47d.png)

**Comment by ArtpokeBr** [comment]
Oxi, bizarro ter as Dusts do Meka, mas tudo bem, será corrigido =)
