### ISSUE TITLE
The Assembler is not a Crafting Table

### ISSUE THREAD

**Issue by IncandescenceSy** [ArtpokeBr/Pluma-a-Journey-to-the-Future#49]
Some Assembling Machine recipes spread the items out as if they are Crafting Table recipes. All recipes in GregTech machines should have all items stacked when possible, and not spread out like this under any circumstances. It just looks silly and is annoying to the player, especially when attempting to automate things.

![image](https://user-images.githubusercontent.com/76633436/210820657-bd365d01-1407-4ea7-b0cc-28f0901d952f.png)
![image](https://user-images.githubusercontent.com/76633436/210820682-01dcdec3-32e2-4f49-b480-1114f1c11363.png)
![image](https://user-images.githubusercontent.com/76633436/210820693-b1197ae3-f958-4fb5-95cc-5a894b0bd0f3.png)
![image](https://user-images.githubusercontent.com/76633436/210820897-f313bf20-2bd1-4fa7-a50b-cf1b66de0fa3.png)

By the way, the link to the Github repo for this pack that is on the Curseforge page gives a 404, so you should probably update it.

**Comment by ArtpokeBr** [comment]
Don't worry, the Github issue with CF got fixed. and this issue, is probally going to be fixed next patch! =)
