### ISSUE TITLE
Logistics pipes

### ISSUE THREAD

**Issue by Dewn5228** [ArtpokeBr/Pluma-a-Journey-to-the-Future#51]
### Problema

O logistics pipes está a dar algum problema na versão que ele está, eu mudei de versão para uma stable e voltou a funcionr todo certinho.

### Imagens/Preview
**Sei que o video não é no pluma mas o mesmo erro está a dar no pluma (fiz essa instancia para ver se o erro era do mod ou do pluma)**

https://streamable.com/147t7w
(O video é muito grande para enviar por aqui)

**Comment by ArtpokeBr** [comment]
Hmmm, Ok, vou revisar as versões e possivelmente trocar para uma Stable realmente.
