### ISSUE TITLE
TConstruct cast missing

### ISSUE THREAD

**Issue by coder-Zzx** [ArtpokeBr/Pluma-a-Journey-to-the-Future#53]
There are some casts missing for example laser-gun-relevant casts and conarm-relevant casts. Maybe you made a mistake or you just ban them or I am just not in the correct stage?

**Comment by ArtpokeBr** [comment]
Hmmm, there are some casts that are disabled, but please, could you provide an image of that? a JEI Search for example.

**Comment by coder-Zzx** [comment]
for example, i cant craft the Laser Medium Cast and Helmet Core Cast!![image](https://user-images.githubusercontent.com/78394728/212949045-d27dd938-7499-4539-906f-8dd51b125a4d.png)
![image](https://user-images.githubusercontent.com/78394728/212949133-6bef6a22-32f8-40f1-b534-77060a5bab1a.png)

**Comment by ArtpokeBr** [comment]
That's why i've asked for a JEI picture haha, you're able to see them in JEI but their recipe is missing? that's it?

**Comment by ArtpokeBr** [comment]
Hmmm, Okay! I'll take a look at it! thx for the report =)
