### ISSUE TITLE
HV questline problems

### ISSUE THREAD

**Issue by OmeletMK** [ArtpokeBr/Pluma-a-Journey-to-the-Future#54]
I think the HV questline have some problems. If I want to make UPIC I need Cleanroom. And If I am going to make the Cleanroom following the questline, it also need cleanroom, so I think the cleanroom task need to put in the front.

**Comment by Quaerere-Git** [comment]
And the production of Agar requires Sterilized Filter Casing and it required at least ZPM.

**Comment by OmeletMK** [comment]
And if you want to complete the best buddy quest it need to complete the Predecessors that you need to make SoC. but if you want to use SoC to make the best lv and mv circuit, it need at least EV circuit assembler.

**Comment by coder-Zzx** [comment]
yeah, i found that too, i think the whole chapter 7 questline needs to redesigned, there's many dead circles.

**Comment by ArtpokeBr** [comment]
Currently on a Vacation, so wont be able to work on it.

But thanks for The Reports guys :)

Keep commenting suggestions as it Will help when I start working on it.

**Comment by OmeletMK** [comment]
The way to get the Ender Pearl you need go to The Twilight Forest to get Fiery Tears, but if you want to get to Twilight Forest, you have to complete the quest A Twilight Crystal and you need to almost complete the Chapter 6, but in Chapter 6 have a quest you need to unlock the quest A liquid from time and space which need at least ZPM, it is the problems previous comments have said. (And the production of Agar requires Sterilized Filter Casing and it required at least ZPM.)

**Comment by coder-Zzx** [comment]
It seems like the enzyme is the key to this problem, maybe you could nerf the recipe of enzyme.

**Comment by ArtpokeBr** [comment]
Ok, found what happened here.

Integrated Processors and Microprocessors (those best buddy circuits) used to have a reworked recipe that downgraded them to HV. I've done a mistake where i've commented the part of the code that contained this some updates ago.

And the Agar situation, it is something that unfortunatly happened during recent updates, I believe that i've wrote that questline before the existence of a Cleanroom! so the recipe used to simply use an HV Autoclave for it. The Solution? now it can be done in an HV Autoclave but it doesn't require a sterile Cleanroom.
