### ISSUE TITLE
Some suggestion for the future

### ISSUE THREAD

**Issue by zjz-Beiming** [ArtpokeBr/Pluma-a-Journey-to-the-Future#57]
can you add more quest about Thaumcraft and iv,luv,zmp and uv for gregtech.
And can you add which world can get the ore in JEI like GTNH

**Comment by ArtpokeBr** [comment]
Don't worry, more Thaumcraft/Magical Quests will be worked on soon! as the pack is only in Beta! =)

Currently trying to fix issues before I introduce new ones.
