### ISSUE TITLE
Chapter 6 and 7 dead circle

### ISSUE THREAD

**Issue by OmeletMK** [ArtpokeBr/Pluma-a-Journey-to-the-Future#60]
If you want to make Eye of Ender to go to The End, you need to go to The Twilight Forest first because you need Fiery Tears to make The Eye of Ender, but if you want to go to The Twilight Forest you must complete the Quest The Twilight Crystal, but if you want to complete the quest, you need to make some developments in Chapter 6. But if you cannot get to The End, you cannot make Melodic Alloy which need Popped Chorus Fruit  to make it. And without Melodic Alloy you cannot make the Time Manipulater which is the important part in the Time Machine, and without Time Machine you cannot make Caminite Blend which is the most important material in the Chapter 6.

**Comment by ArtpokeBr** [comment]
Now the Time Manipulator doesn't require Ultimate Circuits =)

This should fix this dead circle.
