### ISSUE TITLE
Tinkers Construct X Gregtech integration

### ISSUE THREAD

**Issue by Dubl33** [ArtpokeBr/Pluma-a-Journey-to-the-Future#62]
I feel like gregtech is forced way too much into the tinkers construct + armory progression, and you basically can't make any decent tools (except for bronze) up until HV so I feel like it would be better if materials were tiered according to their strength, like some more basic materials made either in the smeltery or LV Extruder, then some in the MV extruder etc. As it stands now the best construct armory armor I can make is some bones and nether material, unless im overlooking something else but most trims, plates and armor cores are gated behind HV extruder, which I feel defeats the purpose of construct armory being an early game way to make armor more easily compared to the vanilla armors.

**Comment by Dubl33** [comment]
ok so i looked again and tools can be made in the lv extruder but I still feel at least some armor materials should be available at lv as well

**Comment by ArtpokeBr** [comment]
Currently on a vacation so can't do much from here haha.

But yeah, maybe it is a good idea to make it  doable at LV or MV actually.
