### ISSUE TITLE
Turbine Rotor Bug

### ISSUE THREAD

**Issue by coder-Zzx** [ArtpokeBr/Pluma-a-Journey-to-the-Future#64]
turbine rotors made of some kinds of material missing
![image](https://user-images.githubusercontent.com/78394728/215380951-cb263caf-6beb-496f-91a9-0f00c2f4d03e.png)
and i dont know where the log is, so if you could tell me that i can also upload the log to help you solve this.

**Comment by ArtpokeBr** [comment]
I believe it should be the latest one, but please try to report this to the GTCEU team as it maybe this is an issue for them to resolve =)
