### ISSUE TITLE
Cursor vanishing

### ISSUE THREAD

**Issue by coder-Zzx** [ArtpokeBr/Pluma-a-Journey-to-the-Future#66]
sometimes the cursor doesnt show. the situation appears randomly and seldom. i guess it's caused by the CustiomCursorMod.

**Comment by ArtpokeBr** [comment]
Hmmm, it could be, maybe if you test enough, you can find exactly what causes it?

Once i'am back home I could also check if this is a common issue with the mod, beacuse if this persists, unfortunatly I'll need to remove the mod =/

**Comment by LeandroSatsuki** [comment]
Tambem acontece comigo, se eu alternar para tela cheia quando ocorre esse erro, automaticamento o jogo fecha.
