### ISSUE TITLE
money of ftbquest turns to 0 after death (a small bug

### ISSUE THREAD

**Issue by Li-ng** [ArtpokeBr/Pluma-a-Journey-to-the-Future#67]
...and it returns while getting another moey through completing new quest
btw,when will pluma get a new update?i REALLY love this modpack and hope it could be updated constantly

**Comment by ArtpokeBr** [comment]
Currently on a Vacation ;) that's why the pack updates stopped a bit, but they'll come back soon!

**Comment by ArtpokeBr** [comment]
Unfortunatly, a common issue with FTB Quests, can't fix it =/
