### ISSUE TITLE
Obtendo Tannin

### ISSUE THREAD

**Issue by LeandroSatsuki** [ArtpokeBr/Pluma-a-Journey-to-the-Future#68]
A primeira linha de missões, já no final.. Existe uma quest chamada "Fermenting Liquids", onde pede para conseguir Tannin, porem achei bem em aberto, pois para fazer o liquido precisei fazer um compressor da segunda linha de quests para fazer uma cera... para poder fazer uma faca e com essa faca arrancar casca de arvore que é um dos ingredientes para processar o liquido.
Outro ponto demorei bastante tempo para descobrir que tinha que colocar água na composteira pra produzir Mulch (outro ingrediente)
Resumindo, achei essa quest muito desconexa da sequencia, sendo que precisei ir bem adiante e voltar para completa-la. caso tenha outra forma de completa-la, dê mais dicas.

**Comment by ArtpokeBr** [comment]
Feito uma Quest, adicionado uma Tooltip na Composting Bin e feito a possibillidade de Pressed Wax ser feita no braço usando ferramentas.
