### ISSUE TITLE
Basic Worktable

### ISSUE THREAD

**Issue by LeandroSatsuki** [ArtpokeBr/Pluma-a-Journey-to-the-Future#69]
Para craftar a Basic Worktable só aparece a opção do ingrediente Treated Wood Plank, que é obtido apenas com um triturador e um compressor, pra quem esta seguindo as quests iniciais fica meio desconexa dessa linha de missões.

**Comment by DatRatVS** [comment]
Acabei de fazer um fix temporário pra esse crafting, e voilá.
[BasicWorktableHotfix.zip](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/files/10715128/BasicWorktableHotfix.zip)
Se quiser aplicar esse fix, coloque o zip anexado na pasta `.minecraft/scripts/` e extraia ela, como no gif de exemplo.
![example](https://user-images.githubusercontent.com/49768896/218289313-02a59cf0-5160-4e0f-a7a8-e6d45023b1fd.gif)
