### ISSUE TITLE
Adventure BackPack (Forestry)

### ISSUE THREAD

**Issue by LeandroSatsuki** [ArtpokeBr/Pluma-a-Journey-to-the-Future#70]
Cada mochila do forestry coleta um tipo de recurso, porém a do Aventureiro deixa em aberto para coletar qualquer tipo de item ( ou item configurados pelo programador ). Percebi que no PLUMA ela não esta aceitanto nenhum tipo de item.

**Comment by ArtpokeBr** [comment]
Acabei implementando algo, agora ela se chama Engineer's Backpack! permitindo o jogador carregar todo tipo de ferramentinha! =)
