### ISSUE TITLE
Crashando quando tem Glass nos favoritos do HEI

### ISSUE THREAD

**Issue by DatRatVS** [ArtpokeBr/Pluma-a-Journey-to-the-Future#72]
`/.minecraft/crash-reports`: [crash-2023-02-12_11.04.36-client.txt](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/files/10727180/crash-2023-02-12_11.04.36-client.txt)
`/.minecraft/hei_bookmarks.ini`: [hei_bookmarks.ini.txt](https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future/files/10727188/hei_bookmarks.ini.txt) (renomeado para .txt pra conseguir upar no github)

Minhas unicas suspeitas são essa maneira em que o id de recipe foi escrito: `crafttweaker:[glass] from [glass shard]` <br>
![image](https://user-images.githubusercontent.com/49768896/218598543-f9bb8c34-1101-464d-adb7-31f94f182956.png)

E provavelmente aconteceria com outros, como por exemplo do Redstone Clock, que eu percebi que também usa os [] <br>
![image](https://user-images.githubusercontent.com/49768896/218598712-5b732b99-34ba-4a0d-90d4-314e4bcbaff0.png)

**Comment by ArtpokeBr** [comment]
Provavelmente isso é um problema do próprio HEI.

tenta reportar isso pro autor lá no Discord da cleanroom e tal.
