### ISSUE TITLE
Energia Magica 

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#75]
Add uma forma para para gerar mana (botania) sem lag 

Add uma forma de gerar essência (thaum) sem gerar taint

**Comment by ArtpokeBr** [comment]
Atualmente existe um Addon to Thaum que permite com 100% de eficiencia fazer essentia.

E Mana ainda precisa ser trabalhado, mas vou limpar o Issue para deixar as coisas mais limpas.
