### ISSUE TITLE
Fix: receita da polished granite errada

### ISSUE THREAD

**Issue by CaioCesarPS** [ArtpokeBr/Pluma-a-Journey-to-the-Future#8]
# Fix 

**Quando** eu clico pra ver a receita da Polished Granite
**Logo** vejo a receita da Cobble Granite assada que vira Granite

![image](https://user-images.githubusercontent.com/37737495/206742252-efed8479-357a-409a-8546-b3648efe0bd9.png)
![image](https://user-images.githubusercontent.com/37737495/206742288-224709e9-82c6-4d14-afe0-d736a2da8416.png)

**Comment by ArtpokeBr** [comment]
Isso infelizmente é por conta de se possível fazer pela Chisel, não tem como eu resolver nesse sentido =/

E aliás, eu menciono na Quest, Early Game esse granito é feito pela Chisel.
