### ISSUE TITLE
How to get polished granite without chisel?

### ISSUE THREAD

**Issue by Xetaxheb** [ArtpokeBr/Pluma-a-Journey-to-the-Future#81]
If you don't have iron and don't have the chisel, how do you progress?

**Comment by ArtpokeBr** [comment]
Well, the Quest Actually Gives you a free Chisel to progress, so it shouldn't be a problem.

**Comment by ArtpokeBr** [comment]
Well, I'll take a look =)

**Comment by ArtpokeBr** [comment]
Added the Chisel as an Emergency Item in FTB Quests, if someone looses it, now it is possible to get it back =)
