### ISSUE TITLE
Transporte de EU

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#83]
https://user-images.githubusercontent.com/88991962/224584076-1eaf9efa-bcac-4b15-a9c7-25278a8a80e2.mp4

Como pode ser visto, os Butters, são inteligentes, aceitando interação com ender io (por ex.)
Sugiro add uma quest na parte energética - Como uma forma de gerar energia sem ser a local

Outra seria usando P2P do ae2 

Relevancia? uma forma de "gerar" energia limpa, fora que é mais simples que transportar Liquidos pra serem queimados nos locais

**Comment by ArtpokeBr** [comment]
É bem Clunky adicionar uma Quest específicamente sobre isso, vou deixar para aqueles que quiserem se desafiar a fazer um sistema desse. =)
