### ISSUE TITLE
Extra Utilities

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#85]
![image](https://user-images.githubusercontent.com/88991962/224777983-f2ab53e6-da98-4f23-af44-a0d25bf68837.png)

![image](https://user-images.githubusercontent.com/88991962/224778033-e23a848f-f5c0-4547-853b-95b9d3cdc173.png)

Sugiro add esse item como recompensa (Ou ao menos, add um texto sobre)

![image](https://user-images.githubusercontent.com/88991962/224778793-3e9dd022-720a-4344-8a54-4ebd11ec2e8e.png)

Basicamente ele serve para organizar a produção com o consumo, ferramenta bem útil

**Comment by ArtpokeBr** [comment]
![image](https://user-images.githubusercontent.com/44851727/225072318-1b32b7b7-4242-4d02-a576-964525adb10b.png)
Pronto, implementado uma menção a ele. =)
