### ISSUE TITLE
Thaumcraft - Recipe

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#9]
Assim como no tinkers, na live passada vc não sabia criar os "dardos' da best, sugiro add uma receita que apareça no jei 
![image](https://user-images.githubusercontent.com/88991962/206871600-67aacde9-7291-4353-9b66-3ba3b2d0a29f.png)

Esse modelo de texto, apesar de ajudar, torna complicado principalmente para quem não entende de inglês

**Comment by Gkiritol** [comment]
![image](https://user-images.githubusercontent.com/88991962/206871688-4a4d9d17-4ff6-40a2-a666-8a768b6de1db.png)
 ou então mudar os itens necessários pra quest, pros itens necessários pra craftar ele

**Comment by ArtpokeBr** [comment]
Ok, um Enhancement Justo.
