### ISSUE TITLE
Totemic: Boss Fight

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#97]
"Arena": O local de Spawn do Boss é dentro dos limites do ritual:
![image](https://user-images.githubusercontent.com/88991962/226781110-093599f1-0707-478e-bb41-72b310724039.png)

Ao delimitar todas as laterais o boss não tem como fugir 
Dessa forma:
![image](https://user-images.githubusercontent.com/88991962/226781406-5762b15b-c474-45d5-930a-b584ab3d1a47.png)
Assim vc o mata com 100% de segurança

Obs.: Para chamar a atenção use ou um arco ou se afaste e volte ai ele se aproxima de vc

Ritual:
usando os 12 sinos como vc ensinou, essa foi a melhor forma que encontrei é 100% de invocar (ficar alternando entre o chocalho e a flauta de osso enquanto pula e bate no tambor  
![image](https://user-images.githubusercontent.com/88991962/226781950-d60af75a-695e-4e1d-b886-cd864c8780a7.png)

Obs.: Sugiro usar o "War Dance" ele dá buffs pra batalha (2 batidas no tambor)

**Comment by ArtpokeBr** [comment]
Mais um detalhe de Documentação que quero ver os jogadores se divertindo encontrando uma forma de lidar com o Boss. não vou entregar a forma mais fácil :p
