### ISSUE TITLE
CA 

### ISSUE THREAD

**Issue by Gkiritol** [ArtpokeBr/Pluma-a-Journey-to-the-Future#98]
![image](https://user-images.githubusercontent.com/88991962/226784797-ca073c7b-e1bc-4917-bd6a-0d926c3f0675.png)

Árvore encontrada no nether 
![image](https://user-images.githubusercontent.com/88991962/226784885-ca350cb2-5126-4616-93a0-80e8017c0ba3.png)

Meu peitoral saiu de 6,48 pra 10,8

**Comment by ArtpokeBr** [comment]
O Construct Armory não é mais um Mod que faz parte da progressão natural do Modpack, então vai caber na consciência da pessoa utilizar coisas quebradas de um Mod adicionado por fora :p
